# Generated by Django 3.1.5 on 2023-01-10 20:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230110_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, region=None, verbose_name='phone'),
        ),
    ]
