# Generated by Django 3.1.5 on 2023-01-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='pickup',
        ),
    ]
