# Generated by Django 3.1.5 on 2023-01-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20230111_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivered', 'Delivered')], default='pickup', max_length=10),
        ),
    ]
