# Generated by Django 3.1.5 on 2023-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20230111_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='braintree_id',
            new_name='transaction_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card')], default='mpesa', max_length=10),
        ),
    ]
