# Generated by Django 3.1.5 on 2023-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20230112_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='first name')),
                ('last_name', models.CharField(max_length=250, verbose_name='last name')),
                ('date', models.CharField(max_length=50, verbose_name='date')),
                ('time', models.CharField(max_length=50, verbose_name='time')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('message', models.TextField()),
            ],
        ),
    ]
