# Generated by Django 3.1.5 on 2023-01-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaTransaction',
        ),
    ]
