# Generated by Django 3.1.5 on 2023-01-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_ravetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravetransaction',
            name='tx_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
