# Generated by Django 3.1.5 on 2023-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('subtitle', models.TextField()),
                ('backdrop', models.ImageField(blank=True, upload_to='features/%Y/%m/%d')),
            ],
        ),
    ]
