# Generated by Django 3.1.5 on 2023-01-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230107_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(db_index=True, max_length=200)),
                ('email', models.CharField(db_index=True, max_length=200)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('subtitle', models.CharField(db_index=True, max_length=200)),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='shop/features')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('position', models.CharField(db_index=True, max_length=200)),
                ('testimony', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
