# Generated by Django 3.1.5 on 2023-01-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preparation_time',
            field=models.IntegerField(default=0),
        ),
    ]
